language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_0aa69ed31211_key -iv $encrypted_0aa69ed31211_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- npm install
script:
- gulp
- mv id_rsa $HOME/.ssh/id_rsa
- chmod +x deploy
- ./deploy
after_script:
- cd ./public
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - hexo
env:
  global:
  - GH_REF: github.com/WincerChan/WincerChan.github.io.git
addons:
  ssh_known_hosts:
    secure: sWW/ImY54rfPFsejkfve/fbjSKF5mTXOvhZojkGBFWjcJ8basYIsdF23yu1V6KsHuJUHJcJLSRf6Gtim92nSSRIKnRO4pSB5ojs3RvBiBA3oS1L8bDHRtpjUY1Iuyft1w0KxCiQ3lLRY/9/zKGOECBB31U0zCD8C5FyUJbJf37oclFY/utL/BvnzhWKDvnb8eUv6N/EZcJvl+bVjKboWwTEL6AD//T746bzwlAsL4/DtaykCbSjihvBPGcN/kkNq4ahRksrgfhip4SYK1CMDwrXykuxDOVnFjKZCsuBByH7VguexSouI+KfMLFJtSWcW1Rt0TOeqsW1wWEiRwn4K7ghOYABDO8K9jEyqKL4qVgPMp1rK9LurNfUjooqmcVsLm6Snfx1a6/kGTv9ozdh9fpuCQG8FMsl3IZcyhM7xpZ1yHxkDfcc9ckeVFj1dehJ6tIaQpBlPvEpBIZtnGHyHeUSS9DcS4zylnvapcK7rDHRfBnoZFgwoSgnZ7CBCSdKMC5FkDSEgSai0QqbbOh5xxf6ixPwgjWqvajIQPFNY3A0h2/9CMHHicbsXvBp9yCL1Ht3Z7ypWjCd1ft7cQUJWxgYKBdGZn1tpB5DaklmS2soX/Wi4VVYkmOhdWggcJryQa2B/b6iNgIxEFOuGHCGL8wd0J6EWIv69WRWVLq4aq7k=
