language: node_js       # 设置语言

node_js: stable         # 设置版本

install:
  - npm install         # 安装package
  
script:
  - gulp build          # 生成
  
after_script:
  - cd ./public
  - git init
  - git config user.name "WincerChan"
  - git config user.email "WincerChan@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
  
branches:
  only:
    - hexo
    
env:
  global:
    - GH_REF: github.com/WincerChan/WincerChan.github.io.git
  
