# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wincer's Blog
subtitle: 言念君子，温其如玉。
description: 这里是 @Wincer，喜欢折腾新技术，却没多大耐心。个人博客会写得比较杂，包括日常吐槽、技术踩坑，偶尔会写正经一点的。欢迎订阅 RSS(•̀ᴗ•́)。
author: Wincer
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.itswincer.com
root: /
permalink: posts/:title/
# permalink: posts/:abbrlink/
#permalink_defaults:
abbrlink:
  alg: crc32
  rep: hex

sitemap:
  path: sitemap.xml

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 404.html
  - 403.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: inside
stylus:
  compress: true

search:
  path: search.xml
  field: post
  
index_generator:
  per_page: 6

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
  
category_generator:
  per_page: 10

      # Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:WincerChan/WincerChan.github.io.git
  branch: master
  message: '站点更新:{{now("YYYY-MM-DD HH/mm/ss")}}'

## encrypt plugins
encrypt:
  password: wincer
  template: '
    <div class="encrypt">
        <script>
            var onError = function(error) { $("#enc_error")[0].innerHTML = "密码错误！"; }; function decrypt() { var passwd = $("#enc_passwd input")[0].value; console.log(passwd); doDecrypt(passwd, onError); }
            function EnterPress(e){
                var e = window.event || e;
                if (e.keyCode == 13){
                    decrypt();
                }
            }
        </script>
        <input type="text" onkeydown="EnterPress" onkeypress="EnterPress(event)" style="/* border-radius: 10px; */border-style: groove;/* border: 0px; */border-bottom: 2px solid #0097a7; /* 下划线效果 */border-top:0px;border-left:0px;border-right:0px;height: 30px;width: 61.8%;cursor: auto;font-size: 102%;color: currentColor;outline: none;text-overflow: initial;background: #61616;padding-left: 5px" placeholder="输入密码后请按回车">
        <div id="enc_error" style=" display: inline-block; color: #d84527; font: large; ">
        </div>
    </div>
'

image_stream:
  jquery: false
  jquery_lazyload: false
  img_placeholder: false


pwa:
  serviceWorker:
    path: /sw-89d1525e.js
    preload:
      urls:
        - /
    opts:
      networkTimeoutSeconds: 2
    routes:
      - pattern: !!js/regexp /blog\.itswincer\.com/
        strategy: cacheFirst
      - pattern: !!js/regexp /cdn\.jsdelivr\.net/
        strategy: cacheFirst
      - pattern: !!js/regexp /gitee\.com/
        strategy: networkFirst
      - pattern: !!js/regexp /res\.cloudinary\.com/
        strategy: cacheFirst
      - pattern: !!js/regexp /ae01\.alicdn\.com/
        strategy: cacheFirst
  priority: 10
