defaults: &defaults
    docker:
        - image: circleci/node:10.4.0
        
version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Initial Submodule
                command: |
                    git submodule sync
                    git submodule update --init
            - run:
                name: Install Denpendence
                command: |
                    dd if=encrypt.des3 | openssl des3 -d -k $pswd | tar zxf -
                    mv encrypt/* source/_posts/
                    sudo yarn global add gulp
                    yarn install && gulp
            - save_cache:
                key: blog-v1-{{ .Revision }}
                paths:
                    - "public"

    deploy:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Update System
                command: |
                    sudo apt-get update && sudo apt-get install rsync
            - restore_cache:
                keys:
                    - blog-v1-{{ .Revision }}
            - run:
                name: Deploy to VPS
                command: |
                    ls
                    mkdir -p ~/.ssh
                    touch ~/.ssh/known_hosts
                    { ssh-keyscan $SSH_IP 2> /dev/null; } >> ~/.ssh/known_hosts
                    rsync -az -v --delete -e ssh public/* $SSH_USER@$SSH_IP:/data/www/hexo/
            - run:
                name: Push to GITHUB
                command: |
                    cd ./public
                    git config --global user.email "${GH_EMAIL}"
                    git config --global user.name "${GH_USER}"
                    git init
                    git add .
                    git commit -m "Circle CI Auto Built: `date +"%Y-%m-%d %H:%M:%S"`"
                    git push --force --quiet "https://${REPO_TOKEN}@${GH_REF}" master:master
            - run:
                name: Push to Gitee
                command: |
                    cd ./public/api
                    git init
                    git add .
                    ssh-keyscan gitee.com,120.55.226.24 >> ~/.ssh/known_hosts
                    git commit -m "Circle CI Auto Push: `date + "%Y-%m-%d %H:%M:%S"`"
                    git push --force --quiet "git@gitee.com:whisk/blog_api.git" master:master



workflows:
    version: 2

    MyBlog-CI:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: hexo
