version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.4.0
        branches:
            only:
                - hexo
        steps:
            - checkout
            - run:
                name: Test
                command: echo "Testing for private repo"
